// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocem.proto

package pem

import (
	fmt "fmt"
	entity "github.com/celer-network/goCeler/entity"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Next tag: 17
type OpenChannelEventType int32

const (
	OpenChannelEventType_UNDEFINED_OPEN_CHANNEL_EVENT_TYPE OpenChannelEventType = 0
	OpenChannelEventType_OPEN_CHANNEL_REQUEST              OpenChannelEventType = 1
	OpenChannelEventType_OPEN_CHANNEL_API                  OpenChannelEventType = 2
	OpenChannelEventType_CHANNEL_MINED                     OpenChannelEventType = 3
	OpenChannelEventType_TCB_REQUEST                       OpenChannelEventType = 4
	OpenChannelEventType_TCB_API                           OpenChannelEventType = 5
)

var OpenChannelEventType_name = map[int32]string{
	0: "UNDEFINED_OPEN_CHANNEL_EVENT_TYPE",
	1: "OPEN_CHANNEL_REQUEST",
	2: "OPEN_CHANNEL_API",
	3: "CHANNEL_MINED",
	4: "TCB_REQUEST",
	5: "TCB_API",
}

var OpenChannelEventType_value = map[string]int32{
	"UNDEFINED_OPEN_CHANNEL_EVENT_TYPE": 0,
	"OPEN_CHANNEL_REQUEST":              1,
	"OPEN_CHANNEL_API":                  2,
	"CHANNEL_MINED":                     3,
	"TCB_REQUEST":                       4,
	"TCB_API":                           5,
}

func (x OpenChannelEventType) String() string {
	return proto.EnumName(OpenChannelEventType_name, int32(x))
}

func (OpenChannelEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea541db467081a71, []int{0}
}

// Next tag: 13
type OpenChannelEventMessage struct {
	Type                 OpenChannelEventType              `protobuf:"varint,1,opt,name=type,proto3,enum=pem.OpenChannelEventType" json:"type,omitempty"`
	Machine              string                            `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	StartTimeStamp       int64                             `protobuf:"varint,3,opt,name=start_time_stamp,json=startTimeStamp,proto3" json:"start_time_stamp,omitempty"`
	EndTimeStamp         int64                             `protobuf:"varint,4,opt,name=end_time_stamp,json=endTimeStamp,proto3" json:"end_time_stamp,omitempty"`
	Peer                 string                            `protobuf:"bytes,5,opt,name=peer,proto3" json:"peer,omitempty"`
	Error                []string                          `protobuf:"bytes,6,rep,name=error,proto3" json:"error,omitempty"`
	TokenAddr            string                            `protobuf:"bytes,7,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	Cid                  string                            `protobuf:"bytes,8,opt,name=cid,proto3" json:"cid,omitempty"`
	ExecutionTimeMs      float32                           `protobuf:"fixed32,9,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	OspToOsp             bool                              `protobuf:"varint,10,opt,name=osp_to_osp,json=ospToOsp,proto3" json:"osp_to_osp,omitempty"`
	ReadableInitializer  string                            `protobuf:"bytes,11,opt,name=readable_initializer,json=readableInitializer,proto3" json:"readable_initializer,omitempty"`
	Initializer          *entity.PaymentChannelInitializer `protobuf:"bytes,12,opt,name=initializer,proto3" json:"initializer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *OpenChannelEventMessage) Reset()         { *m = OpenChannelEventMessage{} }
func (m *OpenChannelEventMessage) String() string { return proto.CompactTextString(m) }
func (*OpenChannelEventMessage) ProtoMessage()    {}
func (*OpenChannelEventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea541db467081a71, []int{0}
}

func (m *OpenChannelEventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenChannelEventMessage.Unmarshal(m, b)
}
func (m *OpenChannelEventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenChannelEventMessage.Marshal(b, m, deterministic)
}
func (m *OpenChannelEventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenChannelEventMessage.Merge(m, src)
}
func (m *OpenChannelEventMessage) XXX_Size() int {
	return xxx_messageInfo_OpenChannelEventMessage.Size(m)
}
func (m *OpenChannelEventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenChannelEventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OpenChannelEventMessage proto.InternalMessageInfo

func (m *OpenChannelEventMessage) GetType() OpenChannelEventType {
	if m != nil {
		return m.Type
	}
	return OpenChannelEventType_UNDEFINED_OPEN_CHANNEL_EVENT_TYPE
}

func (m *OpenChannelEventMessage) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

func (m *OpenChannelEventMessage) GetStartTimeStamp() int64 {
	if m != nil {
		return m.StartTimeStamp
	}
	return 0
}

func (m *OpenChannelEventMessage) GetEndTimeStamp() int64 {
	if m != nil {
		return m.EndTimeStamp
	}
	return 0
}

func (m *OpenChannelEventMessage) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *OpenChannelEventMessage) GetError() []string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OpenChannelEventMessage) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *OpenChannelEventMessage) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *OpenChannelEventMessage) GetExecutionTimeMs() float32 {
	if m != nil {
		return m.ExecutionTimeMs
	}
	return 0
}

func (m *OpenChannelEventMessage) GetOspToOsp() bool {
	if m != nil {
		return m.OspToOsp
	}
	return false
}

func (m *OpenChannelEventMessage) GetReadableInitializer() string {
	if m != nil {
		return m.ReadableInitializer
	}
	return ""
}

func (m *OpenChannelEventMessage) GetInitializer() *entity.PaymentChannelInitializer {
	if m != nil {
		return m.Initializer
	}
	return nil
}

func init() {
	proto.RegisterEnum("pem.OpenChannelEventType", OpenChannelEventType_name, OpenChannelEventType_value)
	proto.RegisterType((*OpenChannelEventMessage)(nil), "pem.OpenChannelEventMessage")
}

func init() { proto.RegisterFile("ocem.proto", fileDescriptor_ea541db467081a71) }

var fileDescriptor_ea541db467081a71 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x6e, 0xd3, 0x4c,
	0x10, 0xc5, 0x3f, 0xc7, 0x49, 0x93, 0x4c, 0xf2, 0xa5, 0xee, 0x12, 0x89, 0x05, 0x81, 0xe4, 0xa2,
	0x82, 0xac, 0x4a, 0x4d, 0x44, 0x79, 0x82, 0x34, 0x35, 0x22, 0x12, 0x71, 0x82, 0xeb, 0x22, 0xc1,
	0x8d, 0xe5, 0xd8, 0xa3, 0x64, 0xd5, 0xec, 0x1f, 0xad, 0xb7, 0x40, 0x78, 0x18, 0x5e, 0x89, 0x57,
	0x42, 0xde, 0x34, 0x6d, 0x8a, 0xb8, 0x9b, 0x39, 0xe7, 0x77, 0x3c, 0x23, 0xcf, 0x02, 0xc8, 0x1c,
	0xf9, 0x40, 0x69, 0x69, 0x24, 0x71, 0x15, 0xf2, 0xe7, 0x5d, 0x14, 0x86, 0x99, 0xcd, 0x56, 0x7a,
	0xf5, 0xdb, 0x85, 0xa7, 0x33, 0x85, 0x62, 0xbc, 0xca, 0x84, 0xc0, 0x75, 0xf8, 0x0d, 0x85, 0x99,
	0x62, 0x59, 0x66, 0x4b, 0x24, 0x67, 0x50, 0x37, 0x1b, 0x85, 0xd4, 0xf1, 0x9d, 0xa0, 0x77, 0xfe,
	0x6c, 0xa0, 0x90, 0x0f, 0xfe, 0x66, 0x93, 0x8d, 0xc2, 0xd8, 0x62, 0x84, 0x42, 0x93, 0x67, 0xf9,
	0x8a, 0x09, 0xa4, 0x35, 0xdf, 0x09, 0xda, 0xf1, 0xae, 0x25, 0x01, 0x78, 0xa5, 0xc9, 0xb4, 0x49,
	0x0d, 0xe3, 0x98, 0x96, 0x26, 0xe3, 0x8a, 0xba, 0xbe, 0x13, 0xb8, 0x71, 0xcf, 0xea, 0x09, 0xe3,
	0x78, 0x55, 0xa9, 0xe4, 0x04, 0x7a, 0x28, 0x8a, 0x7d, 0xae, 0x6e, 0xb9, 0x2e, 0x8a, 0xe2, 0x81,
	0x22, 0x50, 0x57, 0x88, 0x9a, 0x36, 0xec, 0x18, 0x5b, 0x93, 0x3e, 0x34, 0x50, 0x6b, 0xa9, 0xe9,
	0x81, 0xef, 0x06, 0xed, 0x78, 0xdb, 0x90, 0x97, 0x00, 0x46, 0xde, 0xa0, 0x48, 0xb3, 0xa2, 0xd0,
	0xb4, 0x69, 0xf9, 0xb6, 0x55, 0x46, 0x45, 0xa1, 0x89, 0x07, 0x6e, 0xce, 0x0a, 0xda, 0xb2, 0x7a,
	0x55, 0x92, 0x53, 0x38, 0xc2, 0x1f, 0x98, 0xdf, 0x1a, 0x26, 0xc5, 0x76, 0x0d, 0x5e, 0xd2, 0xb6,
	0xef, 0x04, 0xb5, 0xf8, 0xf0, 0xde, 0xa8, 0x36, 0x99, 0x96, 0xe4, 0x05, 0x80, 0x2c, 0x55, 0x6a,
	0x64, 0x2a, 0x4b, 0x45, 0xc1, 0x77, 0x82, 0x56, 0xdc, 0x92, 0xa5, 0x4a, 0xe4, 0xac, 0x54, 0xe4,
	0x2d, 0xf4, 0x35, 0x66, 0x45, 0xb6, 0x58, 0x63, 0xca, 0x04, 0x33, 0x2c, 0x5b, 0xb3, 0x9f, 0xa8,
	0x69, 0xc7, 0x0e, 0x7b, 0xb2, 0xf3, 0x26, 0x0f, 0x16, 0x19, 0x43, 0x67, 0x9f, 0xec, 0xfa, 0x4e,
	0xd0, 0x39, 0x3f, 0x1e, 0xdc, 0x1d, 0x6c, 0x9e, 0x6d, 0x38, 0x0a, 0x73, 0xf7, 0xf7, 0xf7, 0x72,
	0xf1, 0x7e, 0xea, 0xf4, 0x97, 0x03, 0xfd, 0x7f, 0x5d, 0x89, 0xbc, 0x86, 0xe3, 0xeb, 0xe8, 0x32,
	0x7c, 0x3f, 0x89, 0xc2, 0xcb, 0x74, 0x36, 0x0f, 0xa3, 0x74, 0xfc, 0x61, 0x14, 0x45, 0xe1, 0xc7,
	0x34, 0xfc, 0x1c, 0x46, 0x49, 0x9a, 0x7c, 0x99, 0x87, 0xde, 0x7f, 0x84, 0x42, 0xff, 0x91, 0x19,
	0x87, 0x9f, 0xae, 0xc3, 0xab, 0xc4, 0x73, 0x48, 0x1f, 0xbc, 0x47, 0xce, 0x68, 0x3e, 0xf1, 0x6a,
	0xe4, 0x08, 0xfe, 0xdf, 0x09, 0xd3, 0xea, 0xd3, 0x9e, 0x4b, 0x0e, 0xa1, 0x93, 0x8c, 0x2f, 0xee,
	0x93, 0x75, 0xd2, 0x81, 0x66, 0x25, 0x54, 0x81, 0xc6, 0xc5, 0x9b, 0xaf, 0x27, 0x4b, 0x66, 0x56,
	0xb7, 0x8b, 0x41, 0x2e, 0xf9, 0x30, 0xc7, 0x35, 0xea, 0x33, 0x81, 0xe6, 0xbb, 0xd4, 0x37, 0xc3,
	0xa5, 0x1c, 0x57, 0xfd, 0x50, 0x21, 0x5f, 0x1c, 0xd8, 0x17, 0xfa, 0xee, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xfa, 0xd6, 0x32, 0x6e, 0xc2, 0x02, 0x00, 0x00,
}
