// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocem.proto

// import "message.proto";

package pem

import (
	fmt "fmt"
	entity "github.com/celer-network/goCeler/entity"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Next tag: 17
type OpenChannelEventType int32

const (
	OpenChannelEventType_UNDEFINED_TYPE       OpenChannelEventType = 0
	OpenChannelEventType_OPEN_CHANNEL_REQUEST OpenChannelEventType = 1
	OpenChannelEventType_OPEN_CHANNEL_API     OpenChannelEventType = 2
	OpenChannelEventType_CHANNEL_MINED        OpenChannelEventType = 3
	OpenChannelEventType_TCB_REQUEST          OpenChannelEventType = 4
	OpenChannelEventType_TCB_API              OpenChannelEventType = 5
)

var OpenChannelEventType_name = map[int32]string{
	0: "UNDEFINED_TYPE",
	1: "OPEN_CHANNEL_REQUEST",
	2: "OPEN_CHANNEL_API",
	3: "CHANNEL_MINED",
	4: "TCB_REQUEST",
	5: "TCB_API",
}

var OpenChannelEventType_value = map[string]int32{
	"UNDEFINED_TYPE":       0,
	"OPEN_CHANNEL_REQUEST": 1,
	"OPEN_CHANNEL_API":     2,
	"CHANNEL_MINED":        3,
	"TCB_REQUEST":          4,
	"TCB_API":              5,
}

func (x OpenChannelEventType) String() string {
	return proto.EnumName(OpenChannelEventType_name, int32(x))
}

func (OpenChannelEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ea541db467081a71, []int{0}
}

// Next tag: 15
type OpenChannelEventMessage struct {
	Type                 OpenChannelEventType              `protobuf:"varint,1,opt,name=type,proto3,enum=pem.OpenChannelEventType" json:"type,omitempty"`
	Machine              string                            `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	StartTimeStamp       int64                             `protobuf:"varint,3,opt,name=start_time_stamp,json=startTimeStamp,proto3" json:"start_time_stamp,omitempty"`
	EndTimeStamp         int64                             `protobuf:"varint,4,opt,name=end_time_stamp,json=endTimeStamp,proto3" json:"end_time_stamp,omitempty"`
	Peer                 string                            `protobuf:"bytes,5,opt,name=peer,proto3" json:"peer,omitempty"`
	Error                []string                          `protobuf:"bytes,6,rep,name=error,proto3" json:"error,omitempty"`
	TokenAddr            string                            `protobuf:"bytes,7,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	Cid                  string                            `protobuf:"bytes,8,opt,name=cid,proto3" json:"cid,omitempty"`
	ExecutionTimeMs      float32                           `protobuf:"fixed32,9,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	OspToOsp             bool                              `protobuf:"varint,10,opt,name=osp_to_osp,json=ospToOsp,proto3" json:"osp_to_osp,omitempty"`
	ReadableInitializer  string                            `protobuf:"bytes,11,opt,name=readable_initializer,json=readableInitializer,proto3" json:"readable_initializer,omitempty"`
	Initializer          *entity.PaymentChannelInitializer `protobuf:"bytes,12,opt,name=initializer,proto3" json:"initializer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *OpenChannelEventMessage) Reset()         { *m = OpenChannelEventMessage{} }
func (m *OpenChannelEventMessage) String() string { return proto.CompactTextString(m) }
func (*OpenChannelEventMessage) ProtoMessage()    {}
func (*OpenChannelEventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea541db467081a71, []int{0}
}

func (m *OpenChannelEventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenChannelEventMessage.Unmarshal(m, b)
}
func (m *OpenChannelEventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenChannelEventMessage.Marshal(b, m, deterministic)
}
func (m *OpenChannelEventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenChannelEventMessage.Merge(m, src)
}
func (m *OpenChannelEventMessage) XXX_Size() int {
	return xxx_messageInfo_OpenChannelEventMessage.Size(m)
}
func (m *OpenChannelEventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenChannelEventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OpenChannelEventMessage proto.InternalMessageInfo

func (m *OpenChannelEventMessage) GetType() OpenChannelEventType {
	if m != nil {
		return m.Type
	}
	return OpenChannelEventType_UNDEFINED_TYPE
}

func (m *OpenChannelEventMessage) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

func (m *OpenChannelEventMessage) GetStartTimeStamp() int64 {
	if m != nil {
		return m.StartTimeStamp
	}
	return 0
}

func (m *OpenChannelEventMessage) GetEndTimeStamp() int64 {
	if m != nil {
		return m.EndTimeStamp
	}
	return 0
}

func (m *OpenChannelEventMessage) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *OpenChannelEventMessage) GetError() []string {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OpenChannelEventMessage) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *OpenChannelEventMessage) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *OpenChannelEventMessage) GetExecutionTimeMs() float32 {
	if m != nil {
		return m.ExecutionTimeMs
	}
	return 0
}

func (m *OpenChannelEventMessage) GetOspToOsp() bool {
	if m != nil {
		return m.OspToOsp
	}
	return false
}

func (m *OpenChannelEventMessage) GetReadableInitializer() string {
	if m != nil {
		return m.ReadableInitializer
	}
	return ""
}

func (m *OpenChannelEventMessage) GetInitializer() *entity.PaymentChannelInitializer {
	if m != nil {
		return m.Initializer
	}
	return nil
}

func init() {
	proto.RegisterEnum("pem.OpenChannelEventType", OpenChannelEventType_name, OpenChannelEventType_value)
	proto.RegisterType((*OpenChannelEventMessage)(nil), "pem.OpenChannelEventMessage")
}

func init() { proto.RegisterFile("ocem.proto", fileDescriptor_ea541db467081a71) }

var fileDescriptor_ea541db467081a71 = []byte{
	// 466 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdd, 0x6e, 0xd3, 0x4e,
	0x10, 0xc5, 0xff, 0x8e, 0x93, 0x26, 0x99, 0xe4, 0x9f, 0xba, 0x43, 0x24, 0x16, 0x04, 0x92, 0x41,
	0x15, 0xb2, 0x2a, 0x35, 0x11, 0xe5, 0x09, 0xd2, 0xd4, 0x88, 0x48, 0xe4, 0x03, 0xd7, 0xbd, 0x80,
	0x1b, 0xcb, 0xb1, 0x47, 0xc9, 0xaa, 0xd9, 0x0f, 0xad, 0xb7, 0x40, 0x78, 0x05, 0x1e, 0x8e, 0x57,
	0x42, 0x76, 0x9a, 0x36, 0x20, 0xee, 0x66, 0xce, 0xf9, 0x1d, 0xcf, 0xc8, 0xb3, 0x00, 0x2a, 0x23,
	0x31, 0xd0, 0x46, 0x59, 0x85, 0xae, 0x26, 0xf1, 0xbc, 0x4b, 0xd2, 0x72, 0xbb, 0xdd, 0x49, 0xaf,
	0x7f, 0xb9, 0xf0, 0x74, 0xae, 0x49, 0x8e, 0xd7, 0xa9, 0x94, 0xb4, 0x09, 0xbf, 0x92, 0xb4, 0x53,
	0x2a, 0x8a, 0x74, 0x45, 0x78, 0x0e, 0x75, 0xbb, 0xd5, 0xc4, 0x1c, 0xdf, 0x09, 0x7a, 0x17, 0xcf,
	0x06, 0x9a, 0xc4, 0xe0, 0x6f, 0x36, 0xde, 0x6a, 0x8a, 0x2a, 0x0c, 0x19, 0x34, 0x45, 0x9a, 0xad,
	0xb9, 0x24, 0x56, 0xf3, 0x9d, 0xa0, 0x1d, 0xed, 0x5b, 0x0c, 0xc0, 0x2b, 0x6c, 0x6a, 0x6c, 0x62,
	0xb9, 0xa0, 0xa4, 0xb0, 0xa9, 0xd0, 0xcc, 0xf5, 0x9d, 0xc0, 0x8d, 0x7a, 0x95, 0x1e, 0x73, 0x41,
	0xd7, 0xa5, 0x8a, 0xa7, 0xd0, 0x23, 0x99, 0x1f, 0x72, 0xf5, 0x8a, 0xeb, 0x92, 0xcc, 0x1f, 0x29,
	0x84, 0xba, 0x26, 0x32, 0xac, 0x51, 0x8d, 0xa9, 0x6a, 0xec, 0x43, 0x83, 0x8c, 0x51, 0x86, 0x1d,
	0xf9, 0x6e, 0xd0, 0x8e, 0x76, 0x0d, 0xbe, 0x04, 0xb0, 0xea, 0x96, 0x64, 0x92, 0xe6, 0xb9, 0x61,
	0xcd, 0x8a, 0x6f, 0x57, 0xca, 0x28, 0xcf, 0x0d, 0x7a, 0xe0, 0x66, 0x3c, 0x67, 0xad, 0x4a, 0x2f,
	0x4b, 0x3c, 0x83, 0x13, 0xfa, 0x4e, 0xd9, 0x9d, 0xe5, 0x4a, 0xee, 0xd6, 0x10, 0x05, 0x6b, 0xfb,
	0x4e, 0x50, 0x8b, 0x8e, 0x1f, 0x8c, 0x72, 0x93, 0x69, 0x81, 0x2f, 0x00, 0x54, 0xa1, 0x13, 0xab,
	0x12, 0x55, 0x68, 0x06, 0xbe, 0x13, 0xb4, 0xa2, 0x96, 0x2a, 0x74, 0xac, 0xe6, 0x85, 0xc6, 0xb7,
	0xd0, 0x37, 0x94, 0xe6, 0xe9, 0x72, 0x43, 0x09, 0x97, 0xdc, 0xf2, 0x74, 0xc3, 0x7f, 0x90, 0x61,
	0x9d, 0x6a, 0xd8, 0x93, 0xbd, 0x37, 0x79, 0xb4, 0x70, 0x0c, 0x9d, 0x43, 0xb2, 0xeb, 0x3b, 0x41,
	0xe7, 0xe2, 0xd5, 0xe0, 0xfe, 0x60, 0x8b, 0x74, 0x2b, 0x48, 0xda, 0xfb, 0xbf, 0x7f, 0x90, 0x8b,
	0x0e, 0x53, 0x67, 0x3f, 0x1d, 0xe8, 0xff, 0xeb, 0x4a, 0x88, 0xd0, 0xbb, 0x99, 0x5d, 0x85, 0xef,
	0x27, 0xb3, 0xf0, 0x2a, 0x89, 0x3f, 0x2f, 0x42, 0xef, 0x3f, 0x64, 0xd0, 0x9f, 0x2f, 0xc2, 0x59,
	0x32, 0xfe, 0x30, 0x9a, 0xcd, 0xc2, 0x8f, 0x49, 0x14, 0x7e, 0xba, 0x09, 0xaf, 0x63, 0xcf, 0xc1,
	0x3e, 0x78, 0x7f, 0x38, 0xa3, 0xc5, 0xc4, 0xab, 0xe1, 0x09, 0xfc, 0xbf, 0x17, 0xa6, 0xe5, 0x77,
	0x3c, 0x17, 0x8f, 0xa1, 0x13, 0x8f, 0x2f, 0x1f, 0x92, 0x75, 0xec, 0x40, 0xb3, 0x14, 0xca, 0x40,
	0xe3, 0xf2, 0xcd, 0x97, 0xd3, 0x15, 0xb7, 0xeb, 0xbb, 0xe5, 0x20, 0x53, 0x62, 0x98, 0xd1, 0x86,
	0xcc, 0xb9, 0x24, 0xfb, 0x4d, 0x99, 0xdb, 0xe1, 0x4a, 0x8d, 0xcb, 0x7e, 0xa8, 0x49, 0x2c, 0x8f,
	0xaa, 0xe7, 0xf8, 0xee, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x8b, 0x4a, 0x7c, 0xaf, 0x02,
	0x00, 0x00,
}
