// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delegate.proto

package delegate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PayOriginNote struct {
	OriginalPayId        [][]byte       `protobuf:"bytes,1,rep,name=original_pay_id,json=originalPayId,proto3" json:"original_pay_id,omitempty"` // Deprecated: Do not use.
	IsRefund             bool           `protobuf:"varint,2,opt,name=is_refund,json=isRefund,proto3" json:"is_refund,omitempty"`
	OriginalPays         []*OriginalPay `protobuf:"bytes,3,rep,name=original_pays,json=originalPays,proto3" json:"original_pays,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PayOriginNote) Reset()         { *m = PayOriginNote{} }
func (m *PayOriginNote) String() string { return proto.CompactTextString(m) }
func (*PayOriginNote) ProtoMessage()    {}
func (*PayOriginNote) Descriptor() ([]byte, []int) {
	return fileDescriptor_55487362895670ce, []int{0}
}

func (m *PayOriginNote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayOriginNote.Unmarshal(m, b)
}
func (m *PayOriginNote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayOriginNote.Marshal(b, m, deterministic)
}
func (m *PayOriginNote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayOriginNote.Merge(m, src)
}
func (m *PayOriginNote) XXX_Size() int {
	return xxx_messageInfo_PayOriginNote.Size(m)
}
func (m *PayOriginNote) XXX_DiscardUnknown() {
	xxx_messageInfo_PayOriginNote.DiscardUnknown(m)
}

var xxx_messageInfo_PayOriginNote proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *PayOriginNote) GetOriginalPayId() [][]byte {
	if m != nil {
		return m.OriginalPayId
	}
	return nil
}

func (m *PayOriginNote) GetIsRefund() bool {
	if m != nil {
		return m.IsRefund
	}
	return false
}

func (m *PayOriginNote) GetOriginalPays() []*OriginalPay {
	if m != nil {
		return m.OriginalPays
	}
	return nil
}

type OriginalPay struct {
	PayId                []byte   `protobuf:"bytes,1,opt,name=pay_id,json=payId,proto3" json:"pay_id,omitempty"`
	PaySrc               []byte   `protobuf:"bytes,2,opt,name=pay_src,json=paySrc,proto3" json:"pay_src,omitempty"`
	PayAmt               []byte   `protobuf:"bytes,3,opt,name=pay_amt,json=payAmt,proto3" json:"pay_amt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginalPay) Reset()         { *m = OriginalPay{} }
func (m *OriginalPay) String() string { return proto.CompactTextString(m) }
func (*OriginalPay) ProtoMessage()    {}
func (*OriginalPay) Descriptor() ([]byte, []int) {
	return fileDescriptor_55487362895670ce, []int{1}
}

func (m *OriginalPay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginalPay.Unmarshal(m, b)
}
func (m *OriginalPay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginalPay.Marshal(b, m, deterministic)
}
func (m *OriginalPay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginalPay.Merge(m, src)
}
func (m *OriginalPay) XXX_Size() int {
	return xxx_messageInfo_OriginalPay.Size(m)
}
func (m *OriginalPay) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginalPay.DiscardUnknown(m)
}

var xxx_messageInfo_OriginalPay proto.InternalMessageInfo

func (m *OriginalPay) GetPayId() []byte {
	if m != nil {
		return m.PayId
	}
	return nil
}

func (m *OriginalPay) GetPaySrc() []byte {
	if m != nil {
		return m.PaySrc
	}
	return nil
}

func (m *OriginalPay) GetPayAmt() []byte {
	if m != nil {
		return m.PayAmt
	}
	return nil
}

func init() {
	proto.RegisterType((*PayOriginNote)(nil), "delegate.PayOriginNote")
	proto.RegisterType((*OriginalPay)(nil), "delegate.OriginalPay")
}

func init() { proto.RegisterFile("delegate.proto", fileDescriptor_55487362895670ce) }

var fileDescriptor_55487362895670ce = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x49, 0xcd, 0x49,
	0x4d, 0x4f, 0x2c, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xa6,
	0x30, 0x72, 0xf1, 0x06, 0x24, 0x56, 0xfa, 0x17, 0x65, 0xa6, 0x67, 0xe6, 0xf9, 0xe5, 0x97, 0xa4,
	0x0a, 0x69, 0x71, 0xf1, 0xe7, 0x83, 0x79, 0x89, 0x39, 0xf1, 0x05, 0x89, 0x95, 0xf1, 0x99, 0x29,
	0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x3c, 0x4e, 0x4c, 0x12, 0x8c, 0x41, 0xbc, 0x30, 0xa9, 0x80, 0xc4,
	0x4a, 0xcf, 0x14, 0x21, 0x69, 0x2e, 0xce, 0xcc, 0xe2, 0xf8, 0xa2, 0xd4, 0xb4, 0xd2, 0xbc, 0x14,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x8e, 0xcc, 0xe2, 0x20, 0x30, 0x5f, 0xc8, 0x8a, 0x8b,
	0x17, 0xd9, 0xa0, 0x62, 0x09, 0x66, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x51, 0x3d, 0xb8, 0x63, 0xfc,
	0x11, 0x86, 0x05, 0xf1, 0x20, 0x99, 0x5c, 0xac, 0x14, 0xc6, 0xc5, 0x8d, 0x24, 0x29, 0x24, 0xca,
	0xc5, 0x06, 0x77, 0x0a, 0xa3, 0x06, 0x4f, 0x10, 0x6b, 0x01, 0xd8, 0x7a, 0x71, 0x2e, 0x76, 0x90,
	0x70, 0x71, 0x51, 0x32, 0xd8, 0x72, 0x9e, 0x20, 0x90, 0xaa, 0xe0, 0xa2, 0x64, 0x98, 0x44, 0x62,
	0x6e, 0x89, 0x04, 0x33, 0x5c, 0xc2, 0x31, 0xb7, 0x24, 0x89, 0x0d, 0xec, 0x7f, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x24, 0x85, 0x7a, 0x86, 0x11, 0x01, 0x00, 0x00,
}
