// Code generated by protoc-gen-go. DO NOT EDIT.
// source: osp_report.proto

package ospreport

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OSP voluntarily periodically send OspReport to the Celer Explorer server
type OspReport struct {
	// serialized OspInfo
	OspInfo []byte `protobuf:"bytes,1,opt,name=osp_info,json=ospInfo,proto3" json:"osp_info,omitempty"`
	// signature of osp_info, signed by OSP eth address
	Sig                  []byte   `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OspReport) Reset()         { *m = OspReport{} }
func (m *OspReport) String() string { return proto.CompactTextString(m) }
func (*OspReport) ProtoMessage()    {}
func (*OspReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_467ec2d78d8caea4, []int{0}
}

func (m *OspReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspReport.Unmarshal(m, b)
}
func (m *OspReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspReport.Marshal(b, m, deterministic)
}
func (m *OspReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspReport.Merge(m, src)
}
func (m *OspReport) XXX_Size() int {
	return xxx_messageInfo_OspReport.Size(m)
}
func (m *OspReport) XXX_DiscardUnknown() {
	xxx_messageInfo_OspReport.DiscardUnknown(m)
}

var xxx_messageInfo_OspReport proto.InternalMessageInfo

func (m *OspReport) GetOspInfo() []byte {
	if m != nil {
		return m.OspInfo
	}
	return nil
}

func (m *OspReport) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type OspInfo struct {
	// OSP eth address
	EthAddr string `protobuf:"bytes,1,opt,name=eth_addr,json=ethAddr,proto3" json:"eth_addr,omitempty"`
	// UTC unix timestamp in second
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// server public rpc host:port
	RpcHost  string          `protobuf:"bytes,3,opt,name=rpc_host,json=rpcHost,proto3" json:"rpc_host,omitempty"`
	OspPeers []*PeerBalances `protobuf:"bytes,4,rep,name=osp_peers,json=ospPeers,proto3" json:"osp_peers,omitempty"`
	// number of payments processed
	Payments int64 `protobuf:"varint,5,opt,name=payments,proto3" json:"payments,omitempty"`
	// accept anyone to connect
	OpenAccept bool `protobuf:"varint,6,opt,name=open_accept,json=openAccept,proto3" json:"open_accept,omitempty"`
	// standard open channel configuration
	StdOpenchanConfigs   []*StdOpenChanConfig `protobuf:"bytes,7,rep,name=std_openchan_configs,json=stdOpenchanConfigs,proto3" json:"std_openchan_configs,omitempty"`
	AdminInfo            *AdminInfo           `protobuf:"bytes,8,opt,name=admin_info,json=adminInfo,proto3" json:"admin_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OspInfo) Reset()         { *m = OspInfo{} }
func (m *OspInfo) String() string { return proto.CompactTextString(m) }
func (*OspInfo) ProtoMessage()    {}
func (*OspInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_467ec2d78d8caea4, []int{1}
}

func (m *OspInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OspInfo.Unmarshal(m, b)
}
func (m *OspInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OspInfo.Marshal(b, m, deterministic)
}
func (m *OspInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OspInfo.Merge(m, src)
}
func (m *OspInfo) XXX_Size() int {
	return xxx_messageInfo_OspInfo.Size(m)
}
func (m *OspInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OspInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OspInfo proto.InternalMessageInfo

func (m *OspInfo) GetEthAddr() string {
	if m != nil {
		return m.EthAddr
	}
	return ""
}

func (m *OspInfo) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *OspInfo) GetRpcHost() string {
	if m != nil {
		return m.RpcHost
	}
	return ""
}

func (m *OspInfo) GetOspPeers() []*PeerBalances {
	if m != nil {
		return m.OspPeers
	}
	return nil
}

func (m *OspInfo) GetPayments() int64 {
	if m != nil {
		return m.Payments
	}
	return 0
}

func (m *OspInfo) GetOpenAccept() bool {
	if m != nil {
		return m.OpenAccept
	}
	return false
}

func (m *OspInfo) GetStdOpenchanConfigs() []*StdOpenChanConfig {
	if m != nil {
		return m.StdOpenchanConfigs
	}
	return nil
}

func (m *OspInfo) GetAdminInfo() *AdminInfo {
	if m != nil {
		return m.AdminInfo
	}
	return nil
}

type PeerBalances struct {
	Peer                 string            `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Balances             []*ChannelBalance `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PeerBalances) Reset()         { *m = PeerBalances{} }
func (m *PeerBalances) String() string { return proto.CompactTextString(m) }
func (*PeerBalances) ProtoMessage()    {}
func (*PeerBalances) Descriptor() ([]byte, []int) {
	return fileDescriptor_467ec2d78d8caea4, []int{2}
}

func (m *PeerBalances) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerBalances.Unmarshal(m, b)
}
func (m *PeerBalances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerBalances.Marshal(b, m, deterministic)
}
func (m *PeerBalances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerBalances.Merge(m, src)
}
func (m *PeerBalances) XXX_Size() int {
	return xxx_messageInfo_PeerBalances.Size(m)
}
func (m *PeerBalances) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerBalances.DiscardUnknown(m)
}

var xxx_messageInfo_PeerBalances proto.InternalMessageInfo

func (m *PeerBalances) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *PeerBalances) GetBalances() []*ChannelBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

type ChannelBalance struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	TokenAddr            string   `protobuf:"bytes,2,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	SelfBalance          string   `protobuf:"bytes,3,opt,name=self_balance,json=selfBalance,proto3" json:"self_balance,omitempty"`
	PeerBalance          string   `protobuf:"bytes,4,opt,name=peer_balance,json=peerBalance,proto3" json:"peer_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelBalance) Reset()         { *m = ChannelBalance{} }
func (m *ChannelBalance) String() string { return proto.CompactTextString(m) }
func (*ChannelBalance) ProtoMessage()    {}
func (*ChannelBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_467ec2d78d8caea4, []int{3}
}

func (m *ChannelBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelBalance.Unmarshal(m, b)
}
func (m *ChannelBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelBalance.Marshal(b, m, deterministic)
}
func (m *ChannelBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelBalance.Merge(m, src)
}
func (m *ChannelBalance) XXX_Size() int {
	return xxx_messageInfo_ChannelBalance.Size(m)
}
func (m *ChannelBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelBalance proto.InternalMessageInfo

func (m *ChannelBalance) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *ChannelBalance) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *ChannelBalance) GetSelfBalance() string {
	if m != nil {
		return m.SelfBalance
	}
	return ""
}

func (m *ChannelBalance) GetPeerBalance() string {
	if m != nil {
		return m.PeerBalance
	}
	return ""
}

// standard open channel config
type StdOpenChanConfig struct {
	TokenAddr            string   `protobuf:"bytes,1,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	MinDeposit           string   `protobuf:"bytes,2,opt,name=min_deposit,json=minDeposit,proto3" json:"min_deposit,omitempty"`
	MaxDeposit           string   `protobuf:"bytes,3,opt,name=max_deposit,json=maxDeposit,proto3" json:"max_deposit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StdOpenChanConfig) Reset()         { *m = StdOpenChanConfig{} }
func (m *StdOpenChanConfig) String() string { return proto.CompactTextString(m) }
func (*StdOpenChanConfig) ProtoMessage()    {}
func (*StdOpenChanConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_467ec2d78d8caea4, []int{4}
}

func (m *StdOpenChanConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StdOpenChanConfig.Unmarshal(m, b)
}
func (m *StdOpenChanConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StdOpenChanConfig.Marshal(b, m, deterministic)
}
func (m *StdOpenChanConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StdOpenChanConfig.Merge(m, src)
}
func (m *StdOpenChanConfig) XXX_Size() int {
	return xxx_messageInfo_StdOpenChanConfig.Size(m)
}
func (m *StdOpenChanConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_StdOpenChanConfig.DiscardUnknown(m)
}

var xxx_messageInfo_StdOpenChanConfig proto.InternalMessageInfo

func (m *StdOpenChanConfig) GetTokenAddr() string {
	if m != nil {
		return m.TokenAddr
	}
	return ""
}

func (m *StdOpenChanConfig) GetMinDeposit() string {
	if m != nil {
		return m.MinDeposit
	}
	return ""
}

func (m *StdOpenChanConfig) GetMaxDeposit() string {
	if m != nil {
		return m.MaxDeposit
	}
	return ""
}

type AdminInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Organization         string   `protobuf:"bytes,3,opt,name=organization,proto3" json:"organization,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Website              string   `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminInfo) Reset()         { *m = AdminInfo{} }
func (m *AdminInfo) String() string { return proto.CompactTextString(m) }
func (*AdminInfo) ProtoMessage()    {}
func (*AdminInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_467ec2d78d8caea4, []int{5}
}

func (m *AdminInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminInfo.Unmarshal(m, b)
}
func (m *AdminInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminInfo.Marshal(b, m, deterministic)
}
func (m *AdminInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminInfo.Merge(m, src)
}
func (m *AdminInfo) XXX_Size() int {
	return xxx_messageInfo_AdminInfo.Size(m)
}
func (m *AdminInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AdminInfo proto.InternalMessageInfo

func (m *AdminInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AdminInfo) GetOrganization() string {
	if m != nil {
		return m.Organization
	}
	return ""
}

func (m *AdminInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AdminInfo) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func init() {
	proto.RegisterType((*OspReport)(nil), "ospreport.OspReport")
	proto.RegisterType((*OspInfo)(nil), "ospreport.OspInfo")
	proto.RegisterType((*PeerBalances)(nil), "ospreport.PeerBalances")
	proto.RegisterType((*ChannelBalance)(nil), "ospreport.ChannelBalance")
	proto.RegisterType((*StdOpenChanConfig)(nil), "ospreport.StdOpenChanConfig")
	proto.RegisterType((*AdminInfo)(nil), "ospreport.AdminInfo")
}

func init() { proto.RegisterFile("osp_report.proto", fileDescriptor_467ec2d78d8caea4) }

var fileDescriptor_467ec2d78d8caea4 = []byte{
	// 545 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x53, 0xc1, 0x6e, 0xdb, 0x3a,
	0x10, 0x84, 0x6c, 0x27, 0x96, 0xd6, 0xc6, 0x43, 0x1e, 0x11, 0xa0, 0x4a, 0x91, 0x22, 0x8e, 0x4e,
	0xbe, 0xd4, 0x2e, 0x92, 0x16, 0xe8, 0xd5, 0x71, 0x0f, 0xed, 0xa5, 0x2e, 0xd4, 0x53, 0x7b, 0x11,
	0x68, 0x69, 0x6d, 0x11, 0xb1, 0x48, 0x82, 0x64, 0x90, 0xb4, 0x3f, 0xd0, 0x53, 0x3f, 0xaf, 0xff,
	0x53, 0x2c, 0x45, 0x2b, 0x4e, 0x7a, 0xdb, 0x9d, 0x1d, 0x0e, 0x87, 0xb3, 0x12, 0x9c, 0x28, 0xab,
	0x0b, 0x83, 0x5a, 0x19, 0x37, 0xd3, 0x46, 0x39, 0xc5, 0x12, 0x65, 0x75, 0x0b, 0x64, 0xef, 0x21,
	0x59, 0x59, 0x9d, 0xfb, 0x86, 0x9d, 0x41, 0x4c, 0x5c, 0x21, 0x37, 0x2a, 0x8d, 0x26, 0xd1, 0x74,
	0x9c, 0x0f, 0x95, 0xd5, 0x9f, 0xe4, 0x46, 0xb1, 0x13, 0xe8, 0x5b, 0xb1, 0x4d, 0x7b, 0x1e, 0xa5,
	0x32, 0xfb, 0xd3, 0x83, 0xe1, 0x2a, 0x4c, 0xcf, 0x20, 0x46, 0x57, 0x17, 0xbc, 0xaa, 0x8c, 0x3f,
	0x98, 0xe4, 0x43, 0x74, 0xf5, 0xa2, 0xaa, 0x0c, 0x3b, 0x87, 0xc4, 0x89, 0x06, 0xad, 0xe3, 0x8d,
	0xf6, 0xc7, 0x07, 0xf9, 0x23, 0x40, 0x07, 0x8d, 0x2e, 0x8b, 0x5a, 0x59, 0x97, 0xf6, 0xdb, 0x83,
	0x46, 0x97, 0x1f, 0x95, 0x75, 0xec, 0x2d, 0x90, 0xcd, 0x42, 0x23, 0x1a, 0x9b, 0x0e, 0x26, 0xfd,
	0xe9, 0xe8, 0xea, 0xc5, 0xac, 0x33, 0x3e, 0xfb, 0x82, 0x68, 0x6e, 0xf8, 0x8e, 0xcb, 0x12, 0x6d,
	0x4e, 0xb6, 0x09, 0xb0, 0xec, 0x25, 0xc4, 0x9a, 0xff, 0x68, 0x50, 0x3a, 0x9b, 0x1e, 0x4d, 0xa2,
	0x69, 0x3f, 0xef, 0x7a, 0x76, 0x01, 0x23, 0xa5, 0x51, 0x16, 0xbc, 0x2c, 0x51, 0xbb, 0xf4, 0x78,
	0x12, 0x4d, 0xe3, 0x1c, 0x08, 0x5a, 0x78, 0x84, 0x7d, 0x86, 0x53, 0xeb, 0xaa, 0x82, 0x90, 0xb2,
	0xe6, 0xb2, 0x28, 0x95, 0xdc, 0x88, 0xad, 0x4d, 0x87, 0xfe, 0xf6, 0xf3, 0x83, 0xdb, 0xbf, 0xba,
	0x6a, 0xa5, 0x51, 0x2e, 0x6b, 0x2e, 0x97, 0x9e, 0x94, 0x33, 0xdb, 0x42, 0x65, 0x07, 0x59, 0x76,
	0x0d, 0xc0, 0xab, 0x46, 0xc8, 0x36, 0xd1, 0x78, 0x12, 0x4d, 0x47, 0x57, 0xa7, 0x07, 0x2a, 0x0b,
	0x1a, 0x52, 0x80, 0x79, 0xc2, 0xf7, 0x65, 0xf6, 0x0d, 0xc6, 0x87, 0x6f, 0x63, 0x0c, 0x06, 0x94,
	0x41, 0xc8, 0xd5, 0xd7, 0xec, 0x1d, 0xc4, 0xeb, 0x30, 0x4f, 0x7b, 0xde, 0xdc, 0xd9, 0x81, 0x2c,
	0xb9, 0x92, 0xb8, 0x0b, 0x0a, 0x79, 0x47, 0xcd, 0x7e, 0x45, 0xf0, 0xdf, 0xd3, 0x21, 0xed, 0xb5,
	0x14, 0x55, 0x10, 0xa7, 0x92, 0xbd, 0x02, 0x70, 0xea, 0x96, 0x62, 0xa2, 0x6d, 0xf6, 0xfc, 0x20,
	0xf1, 0x88, 0xdf, 0xe7, 0x25, 0x8c, 0x2d, 0xee, 0x36, 0x45, 0x10, 0x0d, 0x5b, 0x1b, 0x11, 0xb6,
	0xd7, 0xbc, 0x84, 0x31, 0xb9, 0xec, 0x28, 0x83, 0x96, 0xa2, 0x1f, 0x5f, 0x95, 0x39, 0xf8, 0xff,
	0x9f, 0x08, 0x9f, 0xdd, 0x1c, 0x3d, 0xbf, 0xf9, 0x02, 0x46, 0x94, 0x65, 0x85, 0x5a, 0x59, 0xe1,
	0x82, 0x33, 0x68, 0x84, 0xfc, 0xd0, 0x22, 0x9e, 0xc0, 0x1f, 0x3a, 0x42, 0x3f, 0x10, 0xf8, 0x43,
	0x20, 0x64, 0xbf, 0x23, 0x48, 0xba, 0xcc, 0x29, 0x58, 0xc9, 0x1b, 0xdc, 0x07, 0x4b, 0x35, 0x3b,
	0x85, 0x23, 0x6c, 0xb8, 0xd8, 0x05, 0xf5, 0xb6, 0x61, 0x19, 0x8c, 0x95, 0xd9, 0x72, 0x29, 0x7e,
	0x72, 0x27, 0x94, 0x0c, 0xca, 0x4f, 0x30, 0x96, 0xc2, 0x90, 0x6c, 0xa3, 0xb5, 0xe1, 0xbd, 0xfb,
	0x96, 0x26, 0xf7, 0xb8, 0xb6, 0xc2, 0xa1, 0xff, 0x22, 0x93, 0x7c, 0xdf, 0xde, 0x5c, 0x7d, 0x7f,
	0xb3, 0x15, 0xae, 0xbe, 0x5b, 0xcf, 0x4a, 0xd5, 0xcc, 0x4b, 0xdc, 0xa1, 0x79, 0x2d, 0xd1, 0xdd,
	0x2b, 0x73, 0x3b, 0xdf, 0xaa, 0x25, 0xf5, 0x73, 0xa3, 0xee, 0x1c, 0xce, 0xbb, 0xe5, 0xae, 0x8f,
	0xfd, 0x2f, 0x7c, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xb4, 0x69, 0x0b, 0xd6, 0x03, 0x00,
	0x00,
}
